# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-05 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_googledriveinstitutions', '0002_auto_20210401_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesettings',
            name='addon_option',
        ),
    ]
