# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-06-10 03:11
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0179_rdmwebmeetingapps_rdmworkflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdmworkflows',
            name='webhook_url',
            field=osf.utils.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
