# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-08 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0213_auto_20200912_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduPersonEntilement', models.CharField(max_length=50)),
                ('permission', models.BooleanField(default=True)),
            ],
        ),
    ]
