# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-12 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0214_authcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcontrol',
            name='institution',
            field=models.IntegerField(default=0),
        ),
    ]
