# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-12 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0215_authcontrol_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authcontrol',
            old_name='institution',
            new_name='institutionId',
        ),
    ]
