# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-23 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0214_merge_20210312_1440'),
        ('osf', '0216_auto_20210212_0240'),
    ]

    operations = [
    ]
