# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-23 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0217_merge_20210423_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcontrol',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authcontrol',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='authcontrol',
            name='updateUser',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authcontrol',
            name='eduPersonEntilement',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
