# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-07-01 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osf', '0178_rdmwebmeetingapps_rdmworkflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMeetingInformation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=254)),
                ('organizer', models.CharField(max_length=254)),
                ('organizer_fullname', models.CharField(max_length=254)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('join_url', models.TextField(max_length=512)),
                ('meetingid', models.TextField(max_length=512)),
                ('meeting_password', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.RdmWebMeetingApps')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllMeetingInformationAttendeesRelation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('webex_meetings_invitee_id', models.CharField(blank=True, max_length=128, null=True)),
                ('all_meeting_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.AllMeetingInformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_guid', models.CharField(max_length=128)),
                ('fullname', models.CharField(max_length=128)),
                ('microsoft_teams_mail', models.CharField(blank=True, max_length=256, null=True)),
                ('microsoft_teams_user_name', models.CharField(blank=True, max_length=256, null=True)),
                ('webex_meetings_mail', models.CharField(blank=True, max_length=256, null=True)),
                ('webex_meetings_display_name', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NodeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('folder_id', models.TextField(blank=True, null=True)),
                ('folder_name', models.TextField(blank=True, null=True)),
                ('folder_location', models.TextField(blank=True, null=True)),
                ('external_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons_integromat_node_settings', to='osf.ExternalAccount')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons_integromat_node_settings', to='osf.AbstractNode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='nodeWorkflows',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alternative_webhook_url', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('node_settings', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.NodeSettings')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.RdmWorkflows')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('oauth_grants', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons_integromat_user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='workflowExecutionMessages',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notified', models.BooleanField(default=False)),
                ('integromat_msg', models.CharField(max_length=128)),
                ('timestamp', models.CharField(max_length=128)),
                ('node_settings', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.NodeSettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='user_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.UserSettings'),
        ),
        migrations.AddField(
            model_name='attendees',
            name='node_settings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.NodeSettings'),
        ),
        migrations.AddField(
            model_name='allmeetinginformationattendeesrelation',
            name='attendees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.Attendees'),
        ),
        migrations.AddField(
            model_name='allmeetinginformation',
            name='attendees',
            field=models.ManyToManyField(related_name='attendees_meetings', to='addons_integromat.Attendees'),
        ),
        migrations.AddField(
            model_name='allmeetinginformation',
            name='attendees_specific',
            field=models.ManyToManyField(related_name='attendees_specific_meetings', through='addons_integromat.AllMeetingInformationAttendeesRelation', to='addons_integromat.Attendees'),
        ),
        migrations.AddField(
            model_name='allmeetinginformation',
            name='node_settings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.NodeSettings'),
        ),
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('webex_meetings_mail', 'node_settings'), ('user_guid', 'node_settings'), ('microsoft_teams_mail', 'node_settings')]),
        ),
    ]
