# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-17 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0009_auto_20210308_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendees',
            old_name='microsoft_teams_user_object',
            new_name='microsoft_temas_name',
        ),
        migrations.AddField(
            model_name='attendees',
            name='microsoft_teams_attendee_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendees',
            name='webex_meetings_attendee_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendees',
            name='webex_meetings_mail',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendees',
            name='webex_meetings_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
