# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-17 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0010_auto_20210517_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendees',
            old_name='microsoft_temas_name',
            new_name='microsoft_teams_user_name',
        ),
        migrations.RenameField(
            model_name='attendees',
            old_name='webex_meetings_name',
            new_name='webex_meetings_display_name',
        ),
    ]
