# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-17 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0011_auto_20210517_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='microsoft_teams_mail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='microsoft_teams_user_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='webex_meetings_display_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='webex_meetings_mail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
