# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-18 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0012_auto_20210517_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendees',
            old_name='microsoft_teams_attendee_active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='attendees',
            name='webex_meetings_attendee_active',
        ),
    ]
