# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0013_auto_20210518_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttendeeRelation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('webex_meetings_invitee_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='allmeetinginformation',
            name='meeting_password',
            field=osf.utils.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allmeetinginformation',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, through='addons_integromat.MeetingAttendeeRelation', to='addons_integromat.Attendees'),
        ),
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('webex_meetings_mail', 'node_settings'), ('user_guid', 'node_settings'), ('microsoft_teams_mail', 'node_settings')]),
        ),
        migrations.AddField(
            model_name='meetingattendeerelation',
            name='allMeetingInformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.AllMeetingInformation'),
        ),
        migrations.AddField(
            model_name='meetingattendeerelation',
            name='attendees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_integromat.Attendees'),
        ),
    ]
