# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-24 11:17
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0013_auto_20210518_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmeetinginformation',
            name='meeting_password',
            field=osf.utils.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together=set([('webex_meetings_mail', 'node_settings'), ('user_guid', 'node_settings'), ('microsoft_teams_mail', 'node_settings')]),
        ),
    ]
