# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0016_auto_20210526_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmeetinginformation',
            name='organizer_fullname',
            field=models.CharField(default='user', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendees',
            name='fullname',
            field=models.CharField(default='user', max_length=128),
            preserve_default=False,
        ),
    ]
