# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-07-07 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_integromat', '0019_nodeworkflows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='is_active',
        ),
    ]
